### ISSUE TITLE
Watch Face Format Sample : aapt2 is not working.

### ISSUE THREAD

**Issue by choe-apposter** [android/wear-os-samples#1015]
I'm trying to build a Watch Face Format Sample.

When I enter ./build-wff.sh SimpleDigital in the terminal,
Error: AAPT2 not defined, please set and try again
e.g. <sdk-path>/build-tools/<version>/aapt2
It comes out like this.

I'm using a MAC, and I've configured it in the .zsenv file as below.
export PATH=$PATH:$ANDROID_HOME/build-tools/34.0.0

But it doesn't work.

What's interesting is,
If I go from the terminal to the path where the actual adapt2 is and input ./aapt2, it works well, but if I input adapt2, it doesn't work.

How can I test the sample?

**Comment by yschimke** [comment]
There are other issues here.  If it can't find bundletool then it exits without a warning.

**Comment by yschimke** [comment]
Instructions won't work on linux https://stackoverflow.com/questions/53298843/how-do-i-install-bundletool

**Comment by yschimke** [comment]
For your original problem you probably need to run

```
./cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
```
