### ISSUE TITLE
Not able to view Wear App on the playstore 

### ISSUE THREAD

**Issue by pulkeet** [android/wear-os-samples#104]
1. created a release version of the mobile app [which has an embedded wear apk]
2. on the successful installation of the mobile app, the wear app should appear on the Wear PlayStore .but it's not showing.

I can see the wear app on Wear OS by Google on 2.24 but not 2.27
FYI: I had tried running RuntimePermissionWear sample and the issue is happening with my app as well
I even analyzed the Mobile Apk and I can the micro_wear apk embedded in it.
Any help will be appreciated. 
Thank you in advance

**Comment by yschimke** [comment]
We can't help with the play store here.  

Is the app you are expecting in the play store the RuntimePermissionWear sample?

Since this is from June, going to close this out.  I hope you aren't still waiting on an answer.
