### ISSUE TITLE
Refresh WearTilesKotlin

### ISSUE THREAD

**Issue by kul3r4** [android/wear-os-samples#1042]
Update with the latest changes
Use protolayouts
Support of large screen displays
+ Milestone requirements (https://github.com/android/wear-os-samples/milestone/2)

**Comment by ithinkihaveacat** [comment]
Some of this was done via https://github.com/android/wear-os-samples/pull/1118 (thanks @yschimke!).

**Comment by yschimke** [comment]
Only 1 layout. There are more

**Comment by hiroaki404** [comment]
I think task has been completed. Are there any others?

**Comment by ithinkihaveacat** [comment]
Agree this issue is fixed, thanks @hiroaki404!
