### ISSUE TITLE
Deprecated sample referenced in official docs and in other un-depracated sample readme

### ISSUE THREAD

**Issue by tonyhallett** [android/wear-os-samples#1066]
https://issuetracker.google.com/issues/335309991

and
https://github.com/android/wear-os-samples/blob/d2d8510d5807d42c31178c8b9ac2605312d0fa92/WearSpeakerSample/README.md

> If you are looking for simpler examples of Compose on [WearOS], refer to [ComposeStarter](https://github.com/android/wear-os-samples/blob/d2d8510d5807d42c31178c8b9ac2605312d0fa92/ComposeStarter) and [ComposeAdvanced](https://github.com/android/wear-os-samples/blob/d2d8510d5807d42c31178c8b9ac2605312d0fa92/ComposeAdvanced).

**Comment by kul3r4** [comment]
Thank you for reporting, this has been fixed.

**Comment by tonyhallett** [comment]
It has not been fixed in this repository - https://github.com/android/wear-os-samples/blob/main/WearSpeakerSample/README.md

**Comment by kul3r4** [comment]
Thank you for reporting, [https://github.com/android/wear-os-samples/blob/main/WearSpeakerSample/README.md](https://github.com/android/wear-os-samples/blob/main/WearSpeakerSample/README.md) has been updated
