### ISSUE TITLE
Sample app WearVerifyRemoteApp has been removed

### ISSUE THREAD

**Issue by avipars** [android/wear-os-samples#1087]
Is it possible to re-add the app or move it to another repository as the code still should work and helps developers build companion apps...

Additionally, it is "breaking" links in the documentation site for Standalone vs Non-standalone apps https://issuetracker.google.com/issues/338342148

**Comment by yschimke** [comment]
cc @kul3r4 

The code exists on a "deprecated" branch https://github.com/android/wear-os-samples/tree/deprecated/WearVerifyRemoteApp

There are some related samples in horologist.

**Comment by kul3r4** [comment]
Thanks for reporting the broken link.
The page has now been fixed linking to another sample [sample](https://github.com/google/horologist/tree/v0.6.10/datalayer/sample)
