### ISSUE TITLE
Disabling Complications

### ISSUE THREAD

**Issue by 3llomi** [android/wear-os-samples#1140]
Is there a way to enable/disable Watch Face complications based on a condition?

I'm working on a Watch Face where the user can customize it and I want to add the option for the user to enable or disable Complications.

Currently I have this code where I check if the complications are enabled, if so, then I can render (draw) complications, otherwise just don't render it.

```kotlin
 override fun render(
        canvas: Canvas,
        bounds: Rect,
        zonedDateTime: ZonedDateTime,
        sharedAssets: AnalogSharedAssets
    ) {
        if(complicationsEnabled){
            for ((id, complication) in complicationSlotsManager.complicationSlots) {
                complication.render(canvas, zonedDateTime, renderParameters)
        }
    }
        //other drawing code
}
```

Now this works, but the problem is that the watch face still detects the tap gesture on the complication itself even though the complication is not visible at all.

**Comment by garanj** [comment]
For this, you can use `ComplicationSlotsUserStyleSetting`:

https://developer.android.com/reference/androidx/wear/watchface/style/UserStyleSetting.ComplicationSlotsUserStyleSetting

This allows you to configure changes to the complications, such as positioning or visibility and should work for your use case.

**Comment by 3llomi** [comment]
I'm not sure if I can control visibility using `ComplicationSlotsUserStyleSetting`.
Is there any sample for this?

**Comment by garanj** [comment]
You should be able to set `enabled` accordingly : https://github.com/android/wear-os-samples/issues/1140#issuecomment-2214177539

**Comment by 3llomi** [comment]
Thanks! it worked.
