### ISSUE TITLE
Unable to run the Watch Face Format samples

### ISSUE THREAD

**Issue by applesauce9** [android/wear-os-samples#1159]
The README for Watch Face Format Sample says to run the watch face with the following commands. This does not work for me using Android Studio Koala | 2024.1.1 Patch 1
```
adb install watchface/build/outputs/apk/debug/watchface-debug.apk
adb shell am broadcast -a com.google.android.wearable.app.DEBUG_SURFACE --es operation set-watchface --es watchFaceId com.example.simpledigital
```

The install works, but the broadcast returns the following error.

```
Broadcasting: Intent { act=com.google.android.wearable.app.DEBUG_SURFACE flg=0x400000 (has extras) }
Broadcast completed: result=3, data="A component name is required."
```

**Comment by yschimke** [comment]
Which emulator are you using? Can you see if it works on Wear OS 5 https://developer.android.com/training/wearables/versions/5/setup

**Comment by applesauce9** [comment]
I was using "Wear OS Small Round API 30", and I forgot that I had changed my build.gradle to change the minimum SDK to 30. Once I switched to API 33 for the emulator, and changed the minSDK back, it runs. Sorry about that. I'd still like it to work for older SDKs but that's a later problem. Thanks.
