### ISSUE TITLE
RemoteIntent not found error

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#12]
<a href="https://github.com/andrew-codechimp"><img src="https://avatars0.githubusercontent.com/u/1849731?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andrew-codechimp](https://github.com/andrew-codechimp)**
_Tuesday Jan 09, 2018 at 10:21 GMT_
_Originally opened as https://github.com/googlesamples/android-WearVerifyRemoteApp/issues/2_

----

When trying to use this sample I'm getting errors trying to resolve Remote Intent

error: package com.google.android.wearable.intent does not exist
error: cannot find symbol variable RemoteIntent

I'm getting the same on my own project which implemented this as well, updating all dependencies to the latest versions didn't resolve the issue either.

**Comment by alexvanyo** [comment]
Since this refers to the Wearable support library, I'm closing this issue as obsolete. The equivalent functionality should now be provided by the androidx libraries.
