### ISSUE TITLE
Watch Face is not loaded into the emulator

### ISSUE THREAD

**Issue by FFFFFF** [android/wear-os-samples#1235]
Hello there, 

I am testing WFF approach on Ubuntu 20.04.6 LTS with Android Studio Ladybug | 2024.2.1 Patch 3.
- Build the app (watch face) `cd SimpleAnalog` and `./gradlew assembleDebug`
- Install the emulator: `Wear OS Small Round API 33`  
- Run the `emulator -avd Wear_OS_Small_Round_API_33` (no errors). Tried versions: 35.2.10; 35.1.21; 35.4.4.
- Install the app into the emulator: `adb install SimpleAnalog/watchface/build/outputs/apk/debug/watchface-debug.apk` (no errors). The message in the console: Performing Streamed Install Success

What I see in the emulator is different from the preview in the project:
![emulator](https://github.com/user-attachments/assets/5bfd6d4e-ac3b-4d8e-98c4-2e69ff60be55)

I expect:
![preview](https://github.com/user-attachments/assets/9dd3ffd4-f23b-45c4-b039-caba6b1763e5)

Am I expecting too much or doing something wrong?
Thank you in advance!

**Comment by gondwanasoft** [comment]
The watch face might have been installed but not selected at the active watch face. I think the form of the required command is something like:
`adb shell am broadcast -a com.google.android.wearable.app.DEBUG_SURFACE --es operation set-watchface --es watchFaceId WATCHFACE_ID`

Replace WATCHFACE_ID with the value of applicationId from watchface/build.gradle.kts.

Or, if my theory is right, you can probably just swap to it manually on the watch.

**Comment by FFFFFF** [comment]
> `adb shell am broadcast -a com.google.android.wearable.app.DEBUG_SURFACE --es operation set-watchface --es watchFaceId WATCHFACE_ID`

Oh, Man! This works.
