### ISSUE TITLE
Update to include the final version of WearGoogleSignInButton

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#15]
<a href="https://github.com/mores"><img src="https://avatars3.githubusercontent.com/u/1318377?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mores](https://github.com/mores)**
_Sunday Jun 16, 2019 at 11:20 GMT_
_Originally opened as https://github.com/googlesamples/android-WearStandaloneGoogleSignIn/issues/3_

----

"The button included in this sample should be used as throwaway code for all Wear integrations until the final version lands in Play Services, and maintained there going forward."

**Comment by codingjeremy** [comment]
<a href="https://github.com/mores"><img src="https://avatars3.githubusercontent.com/u/1318377?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mores](https://github.com/mores)**
_Sunday Jun 16, 2019 at 11:31 GMT_

----

The documentation on https://developer.android.com/training/wearables/apps/auth-wear does not match this sample code. Where is RC_SIGN_IN ?

**Comment by alexvanyo** [comment]
#202 updates the Google sign-in sample, and uses the provided SignIn button (via View-Compose interop).
