### ISSUE TITLE
Could we set the custom typeface for Text element of Tile?

### ISSUE THREAD

**Issue by stdlam** [android/wear-os-samples#153]
Is there any way to apply the custom typeface into Tile Text element?

**Comment by prodeveloper03** [comment]
can I work on this issue??

**Comment by stdlam** [comment]
> can I work on this issue??

Of course, I glad to see your reply. Do you have any idea?

**Comment by JohnNichol** [comment]
Setting custom fonts in tiles is not allowed as tiles are rendering in a system context and so there are security concerns with loading fonts into a privileged process.
