### ISSUE TITLE
Slight truncation of time (9) in TimeText example

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#158]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/231923/134888239-333a2078-c0a0-4fa0-8de4-7245abcb64e7.png">

cc @alexvanyo 

I tried replicating on a different sample, but ouldn't so I'm not sure if it's the sample code or androidx.wear.widget.CurvedTextView, feel free to close this and I'll raise against that component if you think it can't be in the sample.

**Comment by alexvanyo** [comment]
Interesting, I can reproduce, and I can also reproduce for the title as well.

I have a workaround ready, which is to add some padding to all of the `CurvedTextView`s, but this does feel like a slight miscalculation of the text bounds.
