### ISSUE TITLE
WearableRecyclerView scrollbar on square display

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#16]
<a href="https://github.com/moneytoo"><img src="https://avatars0.githubusercontent.com/u/1071643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [moneytoo](https://github.com/moneytoo)**
_Wednesday Feb 14, 2018 at 21:01 GMT_
_Originally opened as https://github.com/googlesamples/android-WearAccessibilityApp/issues/1_

----

In both this sample and https://github.com/googlesamples/android-WearNotifications, Activities featuring WearableRecyclerView display scrollbar that doesn't take the full display height on watches with square displays. The height of scrollbar is the same as the height of an item. It's ok on round watches but this doesn't look right.
(I know I can tweak ScalingScrollLayoutCallback to make it look better/different but I'm not aware of anything related to the scrollbar there.)

![screenshot_1518641071](https://user-images.githubusercontent.com/1071643/36227426-52075d04-11d1-11e8-98ea-d59732743ce5.png)

The app drawer/launcher looks ok.

![screenshot_1518641108](https://user-images.githubusercontent.com/1071643/36227587-ccd63a32-11d1-11e8-8241-9bc11cab4b4e.png)

I tested it in the latest emulator though.

**Comment by alexvanyo** [comment]
Closing as obsolete. If you are still seeing this issue with the latest versions of `WearableRecyclerView` as provided by androidx.wear, please file an issue there.
