### ISSUE TITLE
Custom Complication

### ISSUE THREAD

**Issue by Trispast** [android/wear-os-samples#169]
These samples are great, I have been able to learn a lot from them as well as some of the code labs provided in creating my custom watch face.  I was able to implement complications, but I would like to draw a custom complication and I have been unable to find information on that process. Could someone create a sample or code lab explaining that process?

**Comment by VladimirWrites** [comment]
I have the same problem. It would be great to have an example of how to customize complications. I guess that `CurrentUserStyleRepository` should be used but I have a hard time figuring it how to use it properly.

**Comment by alexvanyo** [comment]
Hi! Does the https://github.com/android/wear-os-samples/tree/main/WearComplicationDataSourcesTestSuite sample help for  creating a complication?

**Comment by VladimirWrites** [comment]
Hi @alexvanyo! Thank you for answering, and sorry that my question was not clear enough! I was wondering how to customize complications on the presentations side. So when using `CanvasComplicationDrawable`, how do I customize the UI? When using the old library, I am able to set things such as `backgroundColor`, `titleColor`, `textColor`, `borderColor`, `iconColor`, etc. But I don't know how to customize the complication UI when using the new library.

**Comment by alexvanyo** [comment]
Ah gotcha! You can create `ComplicationDrawable`s that are `Drawable`s for the `CanvasComplicationDrawable`, and you can define those in XML or in code. In the new watch face sample, there are 4 of them defined in XML like this one here: https://github.com/android/wear-os-samples/blob/main/WatchFaceAlphaKotlin/app/src/main/res/drawable/complication_blue_style.xml

**Comment by VladimirWrites** [comment]
Currently, I am giving users an option to customize all of these colors. Is there a way to preserve this behavior using the new libraries? Is it possible to change the appearance of the complications dynamically depending on the user's choice in the Settings screen?

**Comment by alexvanyo** [comment]
You can update the styles programatically via properties on https://developer.android.com/reference/kotlin/androidx/wear/watchface/complications/rendering/ComplicationStyle, which you can retrieve from a `ComplicationDrawable`: https://developer.android.com/reference/kotlin/androidx/wear/watchface/complications/rendering/ComplicationDrawable#activeStyle() (one for ambient, and one for active)

It looks like the KDoc for https://developer.android.com/reference/kotlin/androidx/wear/watchface/complications/rendering/ComplicationDrawable has references to methods that don't exist, I'll create a bug to update those.

**Comment by Trispast** [comment]
I guess what I am asking for is more on the layout customization side than the style customization. I want to adjust the image/icon/text position within the complication.  Or change the way the ranged value displays it's data. Based on what you provided I am guessing I have to ignore complicationdrawable and create my own method for drawing them.  But I was hoping there was an official way to do that.

**Comment by alexvanyo** [comment]
I'm going to close this issue as it doesn't directly pertain to a sample. If there is a bug or feature that the `androidx.watchface` library could provide here, please open up an issue for those on the issue tracker!
