### ISSUE TITLE
AcceptDenyDialog  not working in API Level 23

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#17]
<a href="https://github.com/Scienticious"><img src="https://avatars2.githubusercontent.com/u/11726108?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Scienticious](https://github.com/Scienticious)**
_Thursday Jun 21, 2018 at 07:31 GMT_
_Originally opened as https://github.com/googlesamples/android-WearAccessibilityApp/issues/2_

----

AcceptDenyDialog perfectly working in After API 23,
But oneActionDialog.get().show showing the warning i.e Call requires API Level 24
How to Show AcceptDenyDialog in API 23 , is there alternative ?

**Comment by alexvanyo** [comment]
Closing as obsolete for very old versions of Wear OS.
