### ISSUE TITLE
Slight simplification

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#18]
<a href="https://github.com/BoD"><img src="https://avatars0.githubusercontent.com/u/372852?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BoD](https://github.com/BoD)**
_Sunday May 13, 2018 at 12:59 GMT_
_Originally opened as https://github.com/googlesamples/android-WatchFace/issues/16_

----

In the Analog Complication WatchFace sample, the `ComplicationData` are stored in a SparseArray, that, if I'm not mistaken, is not used anywhere.  So this should be removed completely to simplify the sample.

The line where they are saved is: https://github.com/googlesamples/android-WatchFace/blob/master/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/AnalogComplicationWatchFaceService.java#L397

You can see that `mActiveComplicationDataSparseArray` is not used anywhere else.

**Comment by alexvanyo** [comment]
Closing as obsolete since this refers to the Wearable support library method of creating watchfaces.

Custom watchface development should now be done with the androidx.watchface library: https://developer.android.com/jetpack/androidx/releases/wear-watchface
