### ISSUE TITLE
Gradle can't find spotless plugin

### ISSUE THREAD

**Issue by castedmo** [android/wear-os-samples#187]
I have to add this snippet to the `settings.gradle` otherwise Gradle can't find that plugin
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
```

**Comment by alexvanyo** [comment]
Is this still occurring with one of the current samples?

**Comment by castedmo** [comment]
No. Doesn't happen to me anymore.
