### ISSUE TITLE
[WatchFaceAlphaKotlin] How to get bottom inset?

### ISSUE THREAD

**Issue by VladimirWrites** [android/wear-os-samples#188]
I have a special way of handling watches with the chin depending on the size of the bottom inset, and I am trying to migrate that project to the latest libraries, but it seems that there is no way to get that value in the `WatchFaceService` implementation since the `mutableWatchState` variable is internal. 

Here is how the watch face looks right now for the watches with the chin:

| Ticks 1  | Ticks 2  | Ticks 3  | Ticks 4  | 
|---|---|---|---|
| ![Screenshot_1630478322](https://user-images.githubusercontent.com/5979600/131623879-c921c3a5-5646-4e4e-acdd-dddddbe25c97.png)  | ![Screenshot_1630478303](https://user-images.githubusercontent.com/5979600/131623888-78b99e5f-bd62-4b2f-9da2-4bbd7662a596.png)  | ![Screenshot_1630478278](https://user-images.githubusercontent.com/5979600/131623891-294f4c3d-9523-495d-92b9-a33af557eb50.png)  | ![Screenshot_1630478020](https://user-images.githubusercontent.com/5979600/131623896-b91e5451-0a50-40f2-a70b-3c117f9a36f9.png)  |  

Is there a way to migrate this implementation to new libraries?

**Comment by alexvanyo** [comment]
Hi @VladimirWrites !

The chin height should still be retrievable via [`WatchState.chinHeight`](https://developer.android.com/reference/kotlin/androidx/wear/watchface/WatchState#chinHeight()), where `WatchState` is provided to `WatchFaceService.createWatchFace` where you can initialize your `Renderer` and `WatchFace`. Hope that helps!

**Comment by VladimirWrites** [comment]
One more question regarding this. It would be great to also use this value to position complications correctly, but it's not available in 
```kotlin
override fun createComplicationSlotsManager(
        currentUserStyleRepository: CurrentUserStyleRepository
) {}
```
Is there a way to access `chinHeight` in this method? Also, will `createWatchFace` be called before `createComplicationSlotsManager`?
