### ISSUE TITLE
How to get user_name and password

### ISSUE THREAD

**Issue by VijaySharma12** [android/wear-os-samples#192]
How to get these ids-
    public static final String ACCOUNT_TYPE = "com.accountransfer.account.type";
    public static final String KEY_ACCOUNT_NAME = "account_name";
    public static final String KEY_ACCOUNT_PASSWORD = "account_password";
    public static final String KEY_ACCOUNT_ARRAY = "account_array";

Please help us.So i could imporve my code.

**Comment by alexvanyo** [comment]
Hi, I don't believe those strings appear anywhere in this repo?
Closing since this is unrelated.
