### ISSUE TITLE
DataLayer Sample: Phone App can not receive message from wearOS after update targetSdk to 30. 

### ISSUE THREAD

**Issue by haozes** [android/wear-os-samples#196]
After update targetSdk to 30.

Send message from wear App with  ` Wearable.getMessageClient(this).sendMessage`

but phone App  `onMessageReceived` not raised.

change targetSdk to 29,  it works again.

**Comment by haozes** [comment]
the whole message is here :
https://stackoverflow.com/questions/70301115/sending-message-from-wearos-app-to-phone-onmessagerecieved-not-called-after-upd

**Comment by alexvanyo** [comment]
The DataLayer sample just got updated, which included a bump to the target sdk to 30. I couldn't reproduce this issue with the updated sample, can you reproduce with the sample here on a specific device or setup?

**Comment by haozes** [comment]
> The DataLayer sample just got updated, which included a bump to the target sdk to 30. I couldn't reproduce this issue with the updated sample, can you reproduce with the sample here on a specific device or setup?

Thank you for reply.
Finally i got the problem is  China device , the bug can only be produced in China phone. 
and i got a workaround to fix it:
Use service to listen message

**Comment by alexvanyo** [comment]
It sounds like this is resolved? Please reopen if not the case!
