### ISSUE TITLE
Watch Face compose

### ISSUE THREAD

**Issue by thaihuynhxyz** [android/wear-os-samples#203]
Can we use compose to draw a watch face?

**Comment by alexvanyo** [comment]
Not currently, at least in the form of rendering an arbitrary `@Composable` to draw the watchface.

The main reason for this is that watchfaces run in a service and draw to a canvas directly, without any sort of View hierarchy which Compose UI depends on.

However, Compose's state system and other components do provide drawing tools, so it would be possible to have a more Compose-friendly way to draw a watchface, even if it doesn't use any Compose UI components.

A tracking issue for that feature is [here](https://issuetracker.google.com/issues/213347389), which is strongly related to another issue for drawing a live wallpaper [here](https://issuetracker.google.com/issues/212430045)
