### ISSUE TITLE
Is TimeZoneReceiver really needed?

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#21]
<a href="https://github.com/VladimirWrites"><img src="https://avatars3.githubusercontent.com/u/5979600?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [VladimirWrites](https://github.com/VladimirWrites)**
_Saturday Jul 21, 2018 at 17:52 GMT_
_Originally opened as https://github.com/googlesamples/android-WatchFace/issues/20_

----

This is more of a question and not an issue.
According to the documentation `onTimeTick` inside `WatchFaceService.Engine` will be called when the time-zone is changed.
https://developer.android.com/reference/android/support/wearable/watchface/WatchFaceService.Engine.html#onTimeTick()
Would it be enough to call 
```
 mCalendar.setTimeZone(TimeZone.getDefault());
 invalidate();
```
inside `onTimeTick()` and not use `BroadcastReceiver` to handle the change like it's done in this project?

https://github.com/googlesamples/android-WatchFace/blob/88ae4adfabdcf3c432d957b84f6fe069b3c8ed14/Wearable/src/main/java/com/example/android/wearable/watchface/watchface/AnalogComplicationWatchFaceService.java#L186-L193

**Comment by alexvanyo** [comment]
Closing as obsolete, since this refers to the old Wearable support library implementation.

Custom watchface development should now be done with the androidx watchface library: https://developer.android.com/jetpack/androidx/releases/wear-watchface
