### ISSUE TITLE
Update README.md with new screenshots and description for user input components

### ISSUE THREAD

**Issue by shumelchyk** [android/wear-os-samples#216]
Update [README.md](https://github.com/android/wear-os-samples/blob/main/ComposeAdvanced/README.md) with new screenshots and description for user input components such as slider, stepper and pickers.

**Comment by shumelchyk** [comment]
@slothwriter created this issue for updating project Readme with latest additions once user input components are fully implemented.

**Comment by yschimke** [comment]
Will update once https://github.com/android/wear-os-samples/pull/332 lands.
