### ISSUE TITLE
Would you accept a new Watch Face sample standing for Ukraine, with some animations?

### ISSUE THREAD

**Issue by LouisCAD** [android/wear-os-samples#225]
Hello, while I'm rooting for peace, many other concerns, and of course, Ukraine, I'm developing a Watch Face and thought I could contribute a new sample with the flag of Ukraine.

I'd like to bring a few animations with clipping to inspire other developers as part of this sample.
As you can see in the video, I animated the wakeup from ambient mode.

If you'd be happy to have a new Watch Face sample from me, I want to tell you that I'd not add this exact "digitalog" design since I want to publish it on the Play Store soon in a freemium app, but the flag would remain of course.

![PXL_20220228_012556850 MP](https://user-images.githubusercontent.com/6975237/155910218-8f5f4485-5176-4905-9775-0c7c0bd6d3f4.jpg)

https://user-images.githubusercontent.com/6975237/155910227-5fa04a84-6a2a-464d-af9c-d4b173fba768.mp4

**Comment by yschimke** [comment]
@codingjeremy Is there a policy or process to answer this?

**Comment by codingjeremy** [comment]
Very nice! I'm not sure on the policy. Let me look into it and follow up.

**Comment by codingjeremy** [comment]
Hi Louis!

I switched teams, but I wanted to follow up.

For this sample in particular, the legal team wants all communication around this to be centralized on the [company blog post(s) related to it](https://blog.google/inside-google/company-announcements/helping-ukraine/) (where we outline some of our actions, etc.).

While that means this repo isn't the right place for it, we highly encourage you to put it in another repository and submit the watch face to the Play Store.

I hope that helps.

Thanks again for contributing to these repos!
