### ISSUE TITLE
Wear OS Samples from Android Studio are broken

### ISSUE THREAD

**Issue by Elodin12** [android/wear-os-samples#230]
I am working in Android Studio, and I followed the directions here: https://developer.android.com/training/wearables/compose-setup 

When it was done downloading, I got an error that states: "In version catalog libs, import of external catalog file failed" basically it looks like it might be looking in the wrong directory for the file. The support link that it mentions just says to make sure I have the file.

Anyone have a way I can set the directory to the right file or do I need to download something else before trying the sample app?
Also if this is not the right place to ask for help pls direct me to where I may find help

**Comment by yschimke** [comment]
Thanks for raising this, a cleanup maintenance change has broken importing the samples.  I'll revert that part of the change.

In the meantime if you download this file and put it in the parent directory (**1 level above**) the project, it should workaround the issue.

https://github.com/android/wear-os-samples/blob/main/gradle/libs.versions.toml
