### ISSUE TITLE
Add end to end test for Android Studio samples

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#232]
Do exactly what Android Studio would do for a checkout, and fail if that is not working on head.

Likely in the form of an additional github workflow that runs daily?

**Comment by yschimke** [comment]
cc @codingjeremy What are the right set of fixes to avoid this happening again?

**Comment by codingjeremy** [comment]
I'm unsure what is wrong?

I renamed the watch face sample and the CI stuff in [this commit](https://github.com/android/wear-os-samples/commit/29fff6718824fe2dd04bc7f347e0b46021b0b5be) and it was green.

**Comment by yschimke** [comment]
Discussed offline: Android Studio still look for WatchFace.

**Comment by yschimke** [comment]
Think this is covered internally, just not obvious publicly.
