### ISSUE TITLE
ComposeStarter Missing Library installing to device, But the simulator is normal

### ISSUE THREAD

**Issue by VapourJ** [android/wear-os-samples#236]
Event Log:   Failed to commit install session 173027019 with command cmd package install-commit 173027019. Error: INSTALL_FAILED_MISSING_SHARED_LIBRARY: 

Package   xxx    requires unavailable shared library com.google.android.wearable; failing!

Try to   uses-library     android:name="com.google.android.wearable"   android:required="false"  in AndroidManifest.xml
But Caused by: java.lang.IllegalStateException: Could not find wearable shared library classes. Please add <uses-library android:name="com.google.android.wearable" android:required="false" /> to the application manifest

This library does not support in China, does it？ Is there any solution？
Thank you in advance

**Comment by yschimke** [comment]
What device are you installing on?

**Comment by VapourJ** [comment]
> 你在什么设备上安装？

Smart watch, Android version 8.1.0

**Comment by yschimke** [comment]
It sounds like a non-Wear OS smartwatch.  If this is not the case, what version of Wear OS does it have?

These libraries only work with Wear OS, but if you do have that, then we should look into why it's failing.

**Comment by LouisCAD** [comment]
WearOS 2.0 is based on Android 7 I think, and the latest AndroidX Wear libraries require Android 8+
