### ISSUE TITLE
Example usage of ComplicationSlot.createEdgeComplicationSlotBuilder with custom shaped rendering

### ISSUE THREAD

**Issue by LouisCAD** [android/wear-os-samples#240]
Hello,

I'm trying to implement complications support on a watch face where I'd let complications take a 5 minutes slice on the edge.
I'm also considering implementing a marquee effect while in interactive mode.

It seems that the `ComplicationSlot.createEdgeComplicationSlotBuilder` function is part of the solution, but I struggle a lot in grasping the API, it seems very complex, and it looks like the API was designed only for circular complication slots. Also, since there's no API guide, it's very hard to know where to start.

Could you add an example where this API is used with custom rendering on a donut slice shape?

Thank you, and have a great day.

**Comment by garanj** [comment]
Hi @LouisCAD 

At the moment the edge complication API is in the early stages and experimental. As a result, rendering is left to the developer, so I appreciate, that's quite a lot to do for the developer.

As an example you can implement your own renderer for the complication, for example:

```
class EdgeCanvasComplication(val boundingArc: BoundingArc): CanvasComplication {
    override fun render(
        canvas: Canvas,
        bounds: Rect,
        zonedDateTime: ZonedDateTime,
        renderParameters: RenderParameters,
        slotId: Int
    ) {
        // Perform rendering inc. using bounding arc
    }
 
    override fun drawHighlight(
        canvas: Canvas,
        bounds: Rect,
        boundsType: Int,
        zonedDateTime: ZonedDateTime,
        color: Int
    ) {
        // Rendering of highlights
    }
 
    override fun getData(): ComplicationData {
        // return ...
    }
 
    override fun loadData(
        complicationData: ComplicationData,
        loadDrawablesAsynchronous: Boolean
    ) {
        // Perform data load
    }
}        
        
// bounding arc required in the render method in order to be able to draw.
fun createEdgeFactory(boundingArc: BoundingArc) = CanvasComplicationFactory { _, _ ->
    EdgeCanvasComplication(boundingArc)
}
        
val edgeComplicationBoundingArc = BoundingArc(0.0f, 90.0f, 10.0f)
val edgeComplication = ComplicationSlot.createEdgeComplicationSlotBuilder(
    id = 101,
    canvasComplicationFactory = createEdgeFactory(edgeComplicationBoundingArc),
    supportedTypes = listOf(
        ComplicationType.RANGED_VALUE,
        ComplicationType.MONOCHROMATIC_IMAGE,
        ComplicationType.SHORT_TEXT,
        ComplicationType.SMALL_IMAGE),
    defaultDataSourcePolicy = DefaultComplicationDataSourcePolicy(
        SystemDataSources.DATA_SOURCE_DAY_OF_WEEK, ComplicationType.SHORT_TEXT
    ),
    bounds = ComplicationSlotBounds(RectF(0.4f, 0.1f, 0.6f, 0.3f)),
    boundingArc = edgeComplicationBoundingArc
).build()
```

Does this help at all?

**Comment by LouisCAD** [comment]
Thank you, there's still a lot to do with no complete example, but I'll try to make something with that. :)
