### ISSUE TITLE
Changes in UserStyleSchema (through app update) are not reflected in the Galaxy Wear app

### ISSUE THREAD

**Issue by LouisCAD** [android/wear-os-samples#242]
Hello,

I'm unsure if there's something wrong in either:
1. The sample
2. androidx.wear.watchface 1.0.1
3. The Samsung Galaxy Wear app (version 2.2.11.22012751)
4. The Samsung Galaxy Watch 4 itself (Wear OS 3.2, R870XXU1EVB4)

How to reproduce:
1. Install the WatchFaceKotlin sample on a Samsung Galaxy Watch 4
2. Open the Galaxy Wear app on the paired smartphone
3. Click "Watch faces"
4. Select "Alpha Analog" to set it
5. Click on the "Customize" blue button
6. Review the settings
7. In the code of the sample, in the `UserStyleSchemaUtils.kt` file, add an extra setting in the list passed to `UserStyleSchema`.
8. Run the `installDebug` Gradle task (don't use the default run action, it would harshly kill the watch face, unsetting it because the [useless] kill action sent by Android Studio is treated as crashing app by Android and Wear OS…)
9. Review the settings in the Galaxy Wear app…

Expected behavior: the newly added setting is present in the Galaxy Wear app.

Actual behavior: the new setting is nowhere to be found in the Galaxy Wear app, even if you leave it until it pops back to the home screen, and open it again.

I hope I can have more information about what's causing this, and of course, a solution that doesn't involve end-user manipulations.

Thank you and have a great day.

**Comment by yschimke** [comment]
@LouisCAD can you raise a buig for this at https://issuetracker.google.com/issues/new?component=1112371&template=1623658

**Comment by yschimke** [comment]
cc @ADClarke

**Comment by LouisCAD** [comment]
@yschimke Done: https://issuetracker.google.com/issues/224590651
