### ISSUE TITLE
Preview bitmap created by EditorSession not matched with the selected color style option

### ISSUE THREAD

**Issue by ngoclanhbrown** [android/wear-os-samples#248]
I have logged the current color style id when `WatchFaceConfigStateHolder.setColorStyle`, the preview bitmap generated by EditorSession isn's matched with the chosen color style.

![Screenshot_20220323_110657](https://user-images.githubusercontent.com/38713308/159622035-1ca18a26-f8e9-43eb-9d13-0562e8c298c1.png)

I have chosen blue style but the preview is the white one,

![Screenshot_20220323_110711](https://user-images.githubusercontent.com/38713308/159622094-dcfa46df-78a8-4b2b-af17-323bdde9a023.png)

When I finished the edit session, the watch face displays on blue style, which is correct.

There are some problem with `EditorSession.renderWatchFaceToBitmap`

**Comment by yschimke** [comment]
We can take a look to confirm whether it's a bug in the sample or the library code.

If you are already sure it's in the library you should raise a bug at https://issuetracker.google.com/issues/new?component=1112371&template=1623658

The samples authors don't work on the library code, and this isn't a bug tracker for it.

**Comment by LouisCAD** [comment]
@ngoclanhbrown Can you link it here please?

**Comment by ngoclanhbrown** [comment]
Hi guys, I have reported the issue to Jetpack team, and they said that the order of the collects is undefined, so in the example app, the `editorSession.userStyle` is collected before `currentUserStyleRepository .userStyle`, which lead to the preview bitmap is rendered with old state. I have added delay to make sure `currentUserStyleRepository .userStyle` in renderer collected before create preview bitmap.

https://issuetracker.google.com/issues/226126158

**Comment by yschimke** [comment]
@ngoclanhbrown Thanks, it will get fixed, but I suspect not in the next week.

If anyone else feels like tackling this, there was a suggestion that a well placed yield, might solve the ordering. PRs would be gratefully accepted, but if will get fixed otherwise if not.

> In WatchFaceConfigStateHolder, we can insert a yield() right before calling createWatchFacePreview call.

https://github.com/android/wear-os-samples/blob/0ab647531c891e7e8f0bc821fc178d8fdd10e4ca/WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/editor/WatchFaceConfigStateHolder.kt#L91

**Comment by ngoclanhbrown** [comment]
@yschimke Thanks for your advice, my app is working normally now.

**Comment by ngoclanhbrown** [comment]
Hi @yschimke, do we have any updates on this issue?

**Comment by yschimke** [comment]
No, all updates would be visible in the bug tracker or PRs.  If you are feeling inclined, I'd be happy to review a PR if you can confirm the fix works.

**Comment by lancelinksp** [comment]
@yschimke Why has the template not been updated despite the fact that @ngoclanhbrown confirmed that adding the yield fixed the problem?

**Comment by yschimke** [comment]
If you submit a PR, I'll be happy to review and submit. It would be much appreciated.

**Comment by lancelinksp** [comment]
@yschimke The PR has been submitted. Thanks for your help

**Comment by yschimke** [comment]
No, a bigger thank you.
