### ISSUE TITLE
Show a warning (Snackbar?) when running a debug build on device

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#254]
Starting to revert https://github.com/android/wear-os-samples/pull/239

and raised https://github.com/android/wear-os-samples/issues/254

**Comment by yschimke** [comment]
This is in place for ComposeAdvanced but needs to be there for others as well.

Also we should look at https://github.com/usefulness/easylauncher-gradle-plugin  to label the build icons.

**Comment by rungrotArunon** [comment]
Be run from mobile phone

**Comment by yschimke** [comment]
@rungrotArunon I don't understand what you mean by this?

**Comment by yschimke** [comment]
closing as low priority
