### ISSUE TITLE
Extension of dealing with broken connection between wearable- and handheld nodes

### ISSUE THREAD

**Issue by codingjeremy** [android/wear-os-samples#27]
<a href="https://github.com/yingding"><img src="https://avatars3.githubusercontent.com/u/1073701?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yingding](https://github.com/yingding)**
_Wednesday Dec 12, 2018 at 14:16 GMT_
_Originally opened as https://github.com/googlesamples/android-DataLayer/issues/6_

----

## Feature Request
Since sometime it is not desired to send data or messages between the wearable and handheld devices in case the (1) bluetooth/wifi connection is off on the phone, (2) watch disconnected in WearOs App, or (3) bluetooth/wifi connection is off on the watch.

The onCapabilityChanged method can be modified to catch the connection status via the available remote nodes by the given capability name. If the reachable wear nodes is empty set, than the data and message exchange can be pause to save RAM and Battery. After the connection between the nodes are reestablished, the data and message exchange shall go on.

**Comment by alexvanyo** [comment]
Closing as obsolete with the rewriting of the DataLayer sample
