### ISSUE TITLE
Have ChannelClient example

### ISSUE THREAD

**Issue by alexmorral** [android/wear-os-samples#31]
It would be nice to have an example on how to use [ChannelClient](https://developers.google.com/android/reference/com/google/android/gms/wearable/ChannelClient) as right now there is not much information on how to use it around internet.

**Comment by kaden-weber** [comment]
Came to post the same issue, also why is the GoogleApiClient used in speedtracker even though it is deprecated?

**Comment by yschimke** [comment]
Going to close this out, it isn't actively being considered as a new sample.

There do appear to be some github projects using it like

https://github.com/njrafi/Wear-Os-Communication/blob/464746ccf616368c4b2f977ccc88d3266b781cea/wear/src/main/java/com/example/communicationdemo/ImageReceiver.kt#L32-L48

And other projects like https://github.com/ichenhe/wear-gallery and https://github.com/ivanmarincic/wear-documents/

**Comment by tberghuis** [comment]
I used ChannelClient in my open source app Wrist Recorder, to send recording files from watch to phone.
https://github.com/tberghuis/WristRecorder
