### ISSUE TITLE
Playstore app on watch does not recognize a user if he bought a watch app via Redeem code, not money.

### ISSUE THREAD

**Issue by gmp009** [android/wear-os-samples#327]
Hi, If a watch face is paid and user used a redeem code on playstore app on mobile now  user get this app on his phone and try to install the watch face from this app to the watch if he press install button it takes him to the playstore app on watch but there it shows still Paid option not install option as watch still believe he have not bought it as he used a redeem code (So technically not bought it but have the the free coupon code for it) is there any fix for it ? If user does not buy watch face but just use redeem code then watch's Playstore should recognize it not like it say ok Pay again then install it on your watch.

**Comment by yschimke** [comment]
This is not a bug reporting system for the playstore app. I'm not actually sure about the right forum for play store bugs, but you could raise against one of the items in https://issuetracker.google.com/issues/new?component=311487&template=1014446

The people monitoring this issue tracker, can't help you with this query.
