### ISSUE TITLE
Return back watch list 

### ISSUE THREAD

**Issue by ploto22** [android/wear-os-samples#331]
I insert into watch details intent a botton and try after "tap" return back to watch list (when i arrived) 
But with any result . . . someone advice ?

**Comment by yschimke** [comment]
Can you provide sample code or a commit against a fork with the problem example.

**Comment by ploto22** [comment]
Hello yschimke
very apprechiate your support. Sorry but i am beginner . . . 
In the WatchDetailScreen.kt  (WatchDetailScreen) i inserted a button 
`                Button(
                    modifier = Modifier
                        .size(ButtonDefaults.ExtraSmallButtonSize)
                        .fillMaxWidth()
                        .absoluteOffset(52.dp, 30.dp),
                    onClick ={ Screen.WatchList.route }`
and i hoped that with onClick and the command "Screen.WatchList.route"  i return back to previuos page (list of the watches). . . unfurtunally dosen't happen . . . some advice ?
Thanks in advance for your time

**Comment by yschimke** [comment]
Not sure you should do this, back is a swipe, shouldn't be a button.

But mechanically it would be

```
            Button(
                modifier = Modifier
                    .size(ButtonDefaults.ExtraSmallButtonSize)
                    .fillMaxWidth()
                    .absoluteOffset(52.dp, 30.dp),
                onClick = { swipeDismissableNavController.popBackStack() }
            ) {
                Text("Back")
            }
```

**Comment by ploto22** [comment]
Too much speed !
Unfortunally
**Unresolved reference: swipeDismissableNavController**

**Comment by yschimke** [comment]
Pass it in to the composable. We can't provide 1:1 development support, so if you are still stuck I would suggest asking in stackoverflow, or kotlinlang slack.

**Comment by ploto22** [comment]
Thanks a lot again . . . i will try
Bye
