### ISSUE TITLE
iOS companion app with WearOS documentation

### ISSUE THREAD

**Issue by pkhivesara** [android/wear-os-samples#34]
Are there any documented APIs that we can use to create an iOS companion app to work with WearOS watchface?
WearOS 2.0 is supposed to be compatible with Android and iOS, however there is no official documentation as to how to achieve this cross platform compatibility

**Comment by codingjeremy** [comment]
There are some APIs that will allow you to do some things with the Wear OS companion app. For instance, in the [WearVerifyRemoteApp](https://github.com/android/wear-os-samples/tree/main/WearVerifyRemoteApp) sample, you can check if your phone app is installed on the iOS side and open the app store listing if the user chooses to do that.

However, it's pretty limited outside of that. If you want to communicate via bluetooth with your phone app or something like that, there isn't an API to do that right now.

Let me know if that doesn't answer the question for you.
