### ISSUE TITLE
WatchFaceKotlin drawing complications other than all at once

### ISSUE THREAD

**Issue by lancelinksp** [android/wear-os-samples#371]
I have added a background complication, which is working fine, however, the images are soo bright that you can not see the rest of the watch. I was going to use drawARGB() to darken the background complication but because all complications are drawn at once I can not have a configuration for the user to be able to darken the background. If I use drawARGB() after the complications are drawn then all of the complication data is darkened instead of just the background complication like I want. Obviously I cant use drawARGB() for that before the complications are drawn because that would not make a difference. I'm guessing there is something I can do to draw the background complication, then the drawARGB(), and then the other complications but I can see to figure out how to separate how they are drawn.

Is there something that I am missing with how the complications are drawn?  Maybe this isn't the place to ask this? Or if there isn't currently a way, can that option be added?

**Comment by yschimke** [comment]
This isn't really the place to ask, but it's not really a bug for https://issuetracker.google.com/.  Can you post a question on stackoverflow and link here, I'll try to get someone on the team to answer there.

**Comment by lancelinksp** [comment]
Thanks @yschimke I posted on stackoverflow https://stackoverflow.com/questions/72253362/drawing-complications-separately-using-watchfacekotlin-wear-os-sample In the future I will keep the questions off of here and save this for issues.
