### ISSUE TITLE
Change one tile sample to show async data fetching

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#396]
Say Fitness, read from Preferences DataStore.

Update in a WorkManager job, out of line from the request.

Our actual guidance would be to avoid all work on a tileRequest and just read form a datastore, so samples should point to that.

**Comment by yschimke** [comment]
cc @ataulm

**Comment by ataulm** [comment]
I do think this is a good idea and I do not have time :D I'll be "done" with my first pass of samples mid-next week, and I can bring you a list of all the questions/use-cases I had while thinking about tiles these past few weeks. 

It would be great to understand if we can demonstrate these in action in samples, but if this is a simple one to do, please go ahead and add me on the PR so I can help review/learn.
