### ISSUE TITLE
new Handler() is deprecated

### ISSUE THREAD

**Issue by lancelinksp** [android/wear-os-samples#45]
new Handler() is deprecated in the WearVerifyRemoteApp MainMobileActivity.java line 88

**Comment by codingjeremy** [comment]
I'm reworking the samples over the next two months. I will make sure to fix this. Thanks for logging it!

**Comment by marcoongithubnow** [comment]
How can i update some TextView  if I put them in other Fragments of the App? At runtime their value is null...
I mean mStateTextView = findViewById(R.id.state)

**Comment by lancelinksp** [comment]
> I'm reworking the samples over the next two months. I will make sure to fix this. Thanks for logging it!

So a couple months has turned into just short of 12 months. Will this ever be fixed?

**Comment by amirrezamirzaei** [comment]
you should close this issue using handler like this is not deprecated!

**Comment by lancelinksp** [comment]
It most definitely is deprecated using it like this. Try using the sample before saying that this use case is not deprecated

**Comment by alexvanyo** [comment]
I just finished up converting https://github.com/android/wear-os-samples/tree/main/WearVerifyRemoteApp to Kotlin and the new `androidx` libraries, which fixed the deprecated `Handler` usage.
