### ISSUE TITLE
I am Gan Wei Xiang from Singapore. My email is ganwx11111@gmail.com. Thanks. I need codingjeremy email to discuss some stuffs.

### ISSUE THREAD

**Issue by ganwx11111** [android/wear-os-samples#47]

**Comment by Tsuyo1003** [comment]
Hello


ganwx11111 <notifications@github.com> 于 2020年7月16日周四 00:42写道：

**Comment by Tsuyo1003** [comment]
What?

**Comment by ganwx11111** [comment]
I am going to sell the app and pay him 50% commission for every app sold.

**Comment by codingjeremy** [comment]
Hi ganwx11111,

Thanks so much for your interest! I am oversubscribed at the time, so I won't be able to take you up on the offer. 

Thank you and good luck with your search!

-Jeremy
