### ISSUE TITLE
Chips are clipped in Golden Tile layouts

### ISSUE THREAD

**Issue by ataulm** [android/wear-os-samples#498]
Some of the Golden Tiles with chips have clipped sides:

- GoldenTilesPreviewsRow1: WorkoutLargeChip, Run
- GoldenTilesPreviewsRow2: MeditationChips, Alarm
- GoldenTilesPreviewsRow3: Media

It's because the default width for `TitleChip` and (regular) `Chip` is `device width - some percent`, however `PrimaryLayout` (which is used in these tile layouts) has some side margins. So where these chips are used in a `PrimaryLayout`, we have to set an explicit width on the chip:

```
.setWidth(DimensionBuilders.ExpandedDimensionProp.Builder().build())
```

**Comment by yschimke** [comment]
Could we detect these in either

a) IDE lint, evaluating the expressions.
b) a debug helper, that validates tiles for common problems?

Or maybe simpler to document these in our samples when we change them?

**Comment by yschimke** [comment]
Maybe this example isn't the same. My concern with the other types of issues I hit like wrap for image, is that they seem like they should be work by eyeball, but silently drop content at runtime.

**Comment by ataulm** [comment]
I think it is the same - for the meditation chips and media examples, if I only added the expanded width to the chips, they disappeared. This is because they were in a column, and the column's default width is "wrap" (the column also needed the expanded width).

convo started in chat about adding lint rules
