### ISSUE TITLE
Not a problem, only a question about WatchFaceKotlin sample

### ISSUE THREAD

**Issue by lancelinksp** [android/wear-os-samples#526]
There is a  section in WatchFaceConfigActivity.kt marked as follows

// TODO (codingjeremy): Replace with a RecyclerView to choose color style (next CL)

Currently the sample randomly picks a color when the setting is tapped.
Is that still the plan? Not trying to be pushy, just curious as that would make the sample much more complete in my opinion.
If this is not the place to ask, please let me know where I should ask similar questions. Thank you!

**Comment by yschimke** [comment]
@codingjeremy doesn't actively work on Wear samples any more. I'm not aware of any current plans, so unless someone corrects me, assume no.

**Comment by yschimke** [comment]
Closing as answered.
