### ISSUE TITLE
BoxInsetLayout analog for Jetpack Compose

### ISSUE THREAD

**Issue by LionZXY** [android/wear-os-samples#538]
Hello! I want to put content in the clock so that it is visible in both the round clock and the square clock. 

![image](https://user-images.githubusercontent.com/5871715/189384128-7f858841-94d7-4615-a9ec-4c79007a9600.png)

There is a BoxInsetLayout in XML, but in Compose I could not find any way to do this.

**Comment by yschimke** [comment]
You can use the fillMaxRectangle modifier from the horologist library for this 

https://google.github.io/horologist/#compose-layout
