### ISSUE TITLE
MessageClient and CapabilityClient with Samsung Galaxy Watch 4

### ISSUE THREAD

**Issue by ryust** [android/wear-os-samples#564]
How do you get MessageClient and CapabilityClient working with a Samsung Galaxy Watch 4 since the Google Wear OS app is not compatible with Samsung's Wear OS 3? The Google Wear OS app needs to be installed for MessageClient and CapabilityClient to work, but the app is not supposed to be installed on Galaxy watches.

There is a catch-22 situation where developers can't use Wear OS software for communication between a phone and Galaxy watch with Wear OS 3. What do we do?

**Comment by yschimke** [comment]
This is not correct.  Galaxy Watch 4 is Wear OS 3, and these do work.

Can you point to why this is not supported?

**Comment by ryust** [comment]
Have you gotten an app using MessageClient working on Wear OS 3 without the Google Wear OS app installed on the phone? It does not work.

Even in the latest Android Studio setting up phone and Wear OS 3 emulator connections, the editor will have you you install the Wear OS app from Google. Try it... I have... and if the Google app is not installed the underlying Wear OS software like MessageClient does not work, but reinstalling it then it works again.

The data layer for Wear OS requires the Google Wear OS app.

**Comment by yschimke** [comment]
Yes, I'm using the datalayer on GW4 with the Samsung Galaxy Wear app. The Google Wear OS app doesn't work with Samsung watches.

**Comment by ryust** [comment]
Yes, I know the Google Wear OS app doesn't work with Samsung... that's my problem. Why does Android Studio new Wear OS tools have you install the Google app? Can you share code that uses MessageClient or CapabilityClient that works between a phone and a companion watch app? It does not work.

**Comment by yschimke** [comment]
That might be a bug in the pairing setup in Android Studio. It shouldn't install that for a real Galaxy Watch device. It does do that for an emulator pair as it should.

There are samples here https://github.com/android/wear-os-samples/search?q=MessageClient

And there are a ton of apps in the Play Store using the data layer on GW4, so it definitely works.

**Comment by ryust** [comment]
I used the examples for the foundation of my app... which is Java, not Kotlin which may be a factor. Do any of the examples use Java?

Just because there are a ton of apps... mine is one of them... doesn't mean all are working on the recent GW4. Again, as soon as I remove the Google Wear OS app, the MessageClient and CapabilityClient stop working. Why is that?

**Comment by yschimke** [comment]
No idea, sorry. Java and Kotlin are not relevant to whether it can pair correctly.

If you have a Samsung watch, you need to pair it with the Samsung Galaxy Wear app.  If that is installed and paired then the data layer should work. 

There was an issue with WearableListenerService on API 33, but this sounds different.  https://developer.android.com/wear/releases#2022-september-20_wearable_sdk_1800

If you are still having issues, you should raise a bug with exact details and a reproduction for example the wear-os-samples project.  This issue tracker is not monitored for issues with pairing.

Raise here https://issuetracker.google.com/issues/new?component=192711&template=840908

**Comment by ryust** [comment]
I am using WearableListenerService which may be related. I'll look at the issue and see if anything there helps and try with latest libraries. Thanks for the feedback.

**Comment by yschimke** [comment]
Not clear any work is needed here.
