### ISSUE TITLE
Update to Compose October '22

### ISSUE THREAD

**Issue by JolandaVerhoef** [android/wear-os-samples#584]
Would be great to update the Compose samples to use the Compose BOM. See https://github.com/android/user-interface-samples/pull/399 for an example of how to do such a migration.

**Comment by shumelchyk** [comment]
Hi @JolandaVerhoef there is a planned update of the samples for Compose for Wear 1.1 version, so can be updated to BOM within these changes.

Can you clarify if BOM can be applied to Compose for Wear too?

cc @yschimke @BowerSteve since we briefly discussed it before.

**Comment by JolandaVerhoef** [comment]
It's not included because the BOM only contains the libraries from the `androidx.compose` library group.

**Comment by oas004** [comment]
According to [this thread](https://kotlinlang.slack.com/archives/C02GBABJUAF/p1668374681824269) in the Kotlin Slack, I understand it like there is no plan to make a BoM for Wear artefacts. Is that still something that should be waited for? Or is this something that can be contributed with the Compose BoM? :)

**Comment by yschimke** [comment]
I think it's worthwhile to make the change, just not complete as there is no planned Wear BOM.

https://github.com/android/wear-os-samples/blob/main/ComposeAdvanced/gradle/libs.versions.toml

<img width="899" alt="image" src="https://user-images.githubusercontent.com/231923/208622838-cb0d3f3c-924b-4fca-ade2-6f8f52dc53e3.png">
