### ISSUE TITLE
Update README for RuntimePermissionsWear sample

### ISSUE THREAD

**Issue by luizgrp** [android/wear-os-samples#587]
The [README](https://github.com/android/wear-os-samples/blob/a49c45cecd01d169f7e863b3f99f2f74aea02fec/RuntimePermissionsWear/README.md?plain=1#L33) file of `RuntimePermissionsWear` sample says:

> wearable apps are not automatically pushed from your mobile device unless you build a production release, see here for more info

This statement makes me think that release apps are automatically pushed from the mobile device to the watch when installed on the mobile device. Is this still the case? If not, then it would be nice to remove it from the docs, or clarify for which OS version that is still valid.

And even if it is still valid, the link that it [points to](https://github.com/android/wear-os-samples/blob/a49c45cecd01d169f7e863b3f99f2f74aea02fec/RuntimePermissionsWear/README.md?plain=1#L33) does not seem to be valid anymore and could be updated / removed from the docs.

**Comment by kul3r4** [comment]
Closing this as `RuntimePermissionsWear` sample has been deprecated.
