### ISSUE TITLE
Send and syncing data between mobile and watch

### ISSUE THREAD

**Issue by JingjingZhangAndPan** [android/wear-os-samples#60]
is it need phone and watch 's package name should be same when to send and syncing data?
when i test, 
if package name is different between phone and watch, 
it's can't to use data layer api to send/receive data.

**Comment by codingjeremy** [comment]
Yes, it is private. From the [DataClient docs](https://developers.google.com/android/reference/com/google/android/gms/wearable/DataClient):

_Data items are private to the application that created them, and are only accessible by that application on other nodes. They should generally be small in size, relying on {@linkplain Asset assets} for the transfer of larger, more persistent data objects such as images._
