### ISSUE TITLE
How to access the raw ppg data

### ISSUE THREAD

**Issue by Maziiiiiii** [android/wear-os-samples#604]
Hi. Is it possible to get the raw heart rate sensor data which is the ppg signal? I want to get the raw PPG signal from the smart watch on the mobile phone and write an APP on the mobile phone. What I found in my searches is that we have access to the heart rate, not the raw signal. Actually, I want the reflected light from the heart rate sensor, which is the PPG signal. Is it possible? and how?

**Comment by yschimke** [comment]
This repository isn't monitored for health api questions.  You could try your luck with https://github.com/android/health-samples

But generally your question is better suited for a site like stackoverflow.
