### ISSUE TITLE
WearVerifyRemoteApp only works on App resume

### ISSUE THREAD

**Issue by saschTa** [android/wear-os-samples#613]
The sample provided in [WearVerifyRemoteApp](https://github.com/android/wear-os-samples/tree/main/WearVerifyRemoteApp)
only works when a wear node is connected during onResume.

Unfortunately this will not handle a case, where user connects to his watch while app is running.

GMS does not provide any way to listen for wear nodes connecting/disconnecting continuously independent of their capabilities. This is required to tell if a install on watch UI is shown or not (More than 0 wear devices connected && 0 wear devices with capability X connected)

**Comment by yschimke** [comment]
You should be able to use WearableListenerService to get events at any time

https://developers.google.com/android/reference/com/google/android/gms/wearable/WearableListenerService#onPeerConnected(com.google.android.gms.wearable.Node)

**Comment by yschimke** [comment]
But thanks for flagging the problem in the sample app

**Comment by saschTa** [comment]
On my devices (Android 12) this event never fires. Is there any special intentfilter that needs to be present?

**Comment by yschimke** [comment]
Let me check, possibly com.google.android.gms.wearable.NODE_CHANGED ?

**Comment by kul3r4** [comment]
The sample is now deprecated
