### ISSUE TITLE
Documentation / comments for Capability Client with the Data Layer API

### ISSUE THREAD

**Issue by ruben-sethi** [android/wear-os-samples#615]
A bit naive but I'm having some trouble understanding how to set up the capabilities across the Wear and companion apps.  I see in the Wear app, there is a `wear.xml` that has some list declaration with a single item, but I can't quite figure out how this is used for filtering capabilities on the companion app side since there don't seem to be any references to this `wear.xml` resource!  I wasn't able to find any other details about this anywhere either (in the developer guides or anything).

**Comment by luizgrp** [comment]
The [wear](https://github.com/android/wear-os-samples/blob/476fad1cc660887146f7123dbf6edee1e54bceda/DataLayer/Wearable/src/main/res/values/wear.xml#L20) capability declared in `wear.xml` file in the **wear** app is referenced [here](https://github.com/android/wear-os-samples/blob/476fad1cc660887146f7123dbf6edee1e54bceda/DataLayer/Application/src/main/java/com/example/android/wearable/datalayer/MainActivity.kt#L258) in the `MainActivity` of the **mobile** app.

Similarly, the [mobile](https://github.com/android/wear-os-samples/blob/476fad1cc660887146f7123dbf6edee1e54bceda/DataLayer/Application/src/main/res/values/wear.xml#L23) capability declared in `wear.xml` file in the **mobile** app is referenced [here](https://github.com/android/wear-os-samples/blob/476fad1cc660887146f7123dbf6edee1e54bceda/DataLayer/Wearable/src/main/java/com/example/android/wearable/datalayer/MainActivity.kt#L138) in the `MainActivity` of the **wear** app.

Details on the developer docs:
- https://developer.android.com/training/wearables/apps/standalone-apps#capability-names
- https://developer.android.com/training/wearables/data/messages#advertise-capabilities

**Comment by ruben-sethi** [comment]
Ah, thank you so much!  I really appreciate the pointers - these are super helpful!
