### ISSUE TITLE
WatchFace Codelab no longer exists

### ISSUE THREAD

**Issue by letalvoj** [android/wear-os-samples#621]
Codelab link in https://github.com/android/wear-os-samples/tree/main/WatchFaceKotlin points back to this repo. No additional information there.

**Comment by ataulm** [comment]
Thanks for the report!

**Comment by ericwomer** [comment]
They haven't updated the Template in Android Studio either, its broken out of the box, and completely removed from Flamingo.

**Comment by ataulm** [comment]
It's unlikely to be fixed in Dolphin/EE because it's been removed in
Flamingo; there's a few places we can improve on developer.android.com for
watch faces (inc. removing reference to the project wizard to avoid
confusion).

**Comment by ericwomer** [comment]
Any reason why it was removed in Flamingo? Any chance they'll bring it back? How are people supposed to create a watch face? Is there a tut on how to create a project manually if they aren't going to bring it back, or do you start with a watch template and convert it over to a watch face?

**Comment by ataulm** [comment]
There were a few reasons including the maintenance vs. usage aspect that
led to its removal. It's not going to come back in Flamingo, but I can't
say whether it'll ever come back 🤷‍♂️

developer.android.com should be sufficient to create a watch face, as well
as the samples on this repo - I'm not sure the template added a lot.

Whether these resources _are_ sufficient is a separate question but adding
issues here for the samples and on issuetracker.google.com for missing /
incorrect aspects on the docs will be appreciated.

**Comment by ericwomer** [comment]
They all start with the Watch Face Template.

**Comment by ataulm** [comment]
Thanks Eric, I think a guide starting from a blank project would be useful :+1: 

Will close this issue as I've removed the link to the deprecated codelab from the Readme. There's nothing to replace it yet, but hopefully that'll be addressed with a guide.
