### ISSUE TITLE
how to import a watch face from wear os companion to android studio

### ISSUE THREAD

**Issue by Patsjemoe** [android/wear-os-samples#63]
hi,
maybe I overlooked it, but I cannot find an explication on how to import a watch face from wear os companion app to android studio. 
I just want to change the position of month/day to day/month, which seems always to be set to US , not to European format.
thanks in advance
regards

**Comment by codingjeremy** [comment]
There is no way to import a third party watch face on your companion app into Android Studio. That would be equivalent of getting source code for an app.

If you want to customize a pre-existing watch face, you will need to recreate the watch face on your own. Sorry. :-/

**Comment by Patsjemoe** [comment]
Hi,
Thank you for your feedback.
Is this also for watch faces made by Google?
Mobvoi said they could not change the watch face (date and month) , because
it belonged to Google... So I assumed that these would be available for use
in android studio... Isn't it...?
Regards


Op zo 22 nov. 2020 20:20 schreef Jeremy Walker <notifications@github.com>:
