### ISSUE TITLE
WatchFaceKotlin: `ColorStyleIdAndResourceIds` & setting CustomValues

### ISSUE THREAD

**Issue by MikeMannox** [android/wear-os-samples#658]
I have started working on designing my first WearOS Watchface & I am using the sample project `WatchFaceKotlin` as a guide. Initially I found it quite confusing to follow how `UserStyleSetting` & `ColorStyleIdAndResourceIds` fits into the architecture, I *think* I am starting to understand it now.

BUT... If I want to give the *User* an option to [say] change just the color of the hands _or_ edit some text on the watchface I am stuck on how I should go about this as `ColorStyleIdAndResourceIds` is an `enum` class with color presets, & therefore is immutable.

An Idea I had is to use the `WatchFaceConfigStateHolder#setMinuteHandArmLength(newLengthRatio: Float)` example  & then apply any colors or strings changes afterward the preset style has been applied. 

However, there is no option to set an `Int` or `String` &  `UserStyleSetting.CustomValueUserStyleSetting.CustomValueOption(customValue: ByteArray)` seems overkill to store a `ColorResource` or `Int` (color value) or a `String`.

- Even `setMinuteHandArmLength` is converting types: `Float` to a `Double` and storing using `UserStyleSetting.DoubleRangeUserStyleSetting.DoubleRangeOption(value: Double)`

@codingjeremy I can see from this [PR](https://github.com/android/wear-os-samples/pull/139) that you designed this mechanism, can you offer some guidance?

Cheers

Mike

**Comment by kul3r4** [comment]
WatchfaceKotlin is now deprecated, please refer to [WatchFaceFormat](https://github.com/android/wear-os-samples/tree/main/WatchFaceFormat) for a sample on how to create WatchFaces
