### ISSUE TITLE
watch face companion app 

### ISSUE THREAD

**Issue by Patsjemoe** [android/wear-os-samples#67]
hi,
Something is not clear to me : if you design a watch face with android studio, do you put the result in the google wear os companion app, or do you create an own companion app for your own watch faces ?
thanks
regards
ludo

**Comment by Patsjemoe** [comment]
Strange that nobody has designed watch faces with android studio.....

**Comment by codingjeremy** [comment]
There isn't a UI in Android Studio to create your watch face. Watch faces have to be manually drawn ([guide](https://developer.android.com/training/wearables/watch-faces/designing)). Though, you can create a default watch face from studio via **`New > New Project > Wear OS > Watch face`**.

There are a couple samples in this repo for them. The [Java one](https://github.com/android/wear-os-samples/tree/main/WatchFace) is already part of the repo and I have a [newer Kotlin one](https://github.com/android/wear-os-samples/tree/alpha-watchface/WatchFaceKotlin) (though it is still going through final review).

Feel free to [watch this video](https://www.youtube.com/watch?v=h6XNyUSrVnQ) for an overview. 

Hopefully, that helps!
