### ISSUE TITLE
Play Store Invalid Data safety form for play-services-wearable:18.0.0

### ISSUE THREAD

**Issue by guahirah** [android/wear-os-samples#681]
Hi,

I cannot make success to upload my Phone app updates using `play-services-wearable` version `18.0.0`
It always got rejected due to `Policy Declaration - Data Safety Section: Personal Info Data Type - Phone number`.

Try to downgrade to the `play-services-wearable` version to `17.1.0,` and the update is approved.
Since WearableListenerService has broken when the app targetting API 33, I cannot use it.

**Comment by yschimke** [comment]
Stackoverflow is the right forum for this https://stackoverflow.com/questions/75343721/policy-declaration-data-safety-section-personal-info-data-type-phone-number
