### ISSUE TITLE
WearVerifyRemote

### ISSUE THREAD

**Issue by rodrigocbapr** [android/wear-os-samples#763]
app is getting node from wear with Weareable.NodeClient , but not with Weareable.getCapability when I call from a bank app where we are integrating, the package names are de same, there are no issues detecting the wear node from capability from the example project, using sames packages name with the smartwatch app. the problem is with the other app with all the existing staff . it was tested using all same configuration gradle and dependencies, to see any issue and works fine in the example project, we cant figure it out why can't work from the existing project calling from there

**Comment by yschimke** [comment]
This isn't a support forum for Wear APIs. You should raise a bug, feel free to link it here. Or try to reproduce with the samples here.

**Comment by yschimke** [comment]
Some quick suggestions. Make sure they are both using the latest play services versions. And also check the signing keys are the same for the paired apps.

**Comment by rodrigocbapr** [comment]
the signing keys seems to be not a problem, without a same signing key works well, the problem is when I do the same with the example but making work in the existing project, Im doing the same from the example and configuration is the same. In example I can get the node of the watch from the capability but doing the same with phone but with project it doesnt work. I dont know where to find help regarding it

**Comment by rodrigocbapr** [comment]
there was a wrong setting in the debug keystore in the watch. my bad.

**Comment by rodrigocbapr** [comment]
> Some quick suggestions. Make sure they are both using the latest play services versions. And also check the signing keys are the same for the paired apps.

there was a wrong setting in the debug keystore in the watch. my bad.
