### ISSUE TITLE
How to send broadcast when tile button is clicked?

### ISSUE THREAD

**Issue by Thomas-Vos** [android/wear-os-samples#80]
I checked out the Wear Tiles Sample and have a question about the buttons.

The tiles media sample contains a Play icon button. As described in the sample, the buttons do not do anything at the moment. However, I am not sure how to set the click action to send a broadcast.

I would assume this play button is supposed to start the music without opening the app. I would like to do something similar, turn on a smart light without opening the app.

However, I cannot find an `ActionBuilders.Action` that sends a broadcast. It would be great if you could add a click action to this sample so it is clear how to actually implement a play button or something similar.

**Comment by joelphilippage** [comment]
I set the ID and then at the beginning of onTileRequest, check request params. If the lastClickableId is your click, you can just run any function there including sending a broadcast. 

Here is my code:

Set Click:
```
.setClickable(ModifiersBuilders.Clickable.builder()
.setId(if(requestParams.state.lastClickableId == START_ID) STOP_ID else START_ID)
.setOnClick(ActionBuilders.LoadAction.builder())))
```

At the beginning of onTileRequest:
```
if(requestParams.state.lastClickableId == START_ID)
            startServer()
        else
            stopServer()
```

My startServer and stopServer functions send broadcasts.

**Comment by alexvanyo** [comment]
It sounds like this is resolved!
