### ISSUE TITLE
How to modify runtime permissions such that it returns the heart rate data from the sensor

### ISSUE THREAD

**Issue by Deepika1498** [android/wear-os-samples#819]
I need the app to return heart rate data whenever Wear Sensors button is clicked on phone or the wearable. How to modify the existing code to do that?

**Comment by ithinkihaveacat** [comment]
Not sure which existing code you're referring to, but suspect you'll have more luck with https://github.com/android/health-samples/tree/main/health-services which focusses on accessing sensor data and health and fitness use cases.
