### ISSUE TITLE
Any updates?(RemoteIntent)

### ISSUE THREAD

**Issue by mikeArcato** [android/wear-os-samples#83]
Hey guys, since this will be a new popular feature to add to new Wear apps would be good to update?
like Kotlin
and also RemoteIntent not found?

if (resultCode == **RemoteIntent**.RESULT_OK) {
                ConfirmationOverlay().showOn(this@MainActivity)
            } else if (resultCode == RemoteIntent.RESULT_FAILED) {
                ConfirmationOverlay()
                    .setType(ConfirmationOverlay.FAILURE_ANIMATION)
                    .showOn(this@MainActivity)
            } else {
                throw IllegalStateException("Unexpected result $resultCode")
            }

**Comment by alexvanyo** [comment]
The `RemoteIntent` functionality has been to migrated `androidx` libraries. Please reopen if there's some functionality missing there that you need.
