### ISSUE TITLE
WearTilesKotlin uses outdated alpha libs

### ISSUE THREAD

**Issue by ArneKoeckeritz** [android/wear-os-samples#84]
Please update the demo to the latest public libs

androidx.wear.tiles:tiles:1.0.0-alpha03
androidx.wear.tiles:tiles-renderer:1.0.0-alpha03

There a huge breaking changes compared to the used old libs.
androidx.wear:wear-tiles:1.0.0-alpha01
androidx.wear:wear-tiles-renderer:1.0.0-alpha01

It's hard to understand what's the recommended implementation.

**Comment by codingjeremy** [comment]
This was revised to the latest version of the API, so it should be addressed. PTAL.

Also, feel free to have a look at the latest code lab: https://developer.android.com/codelabs/wear-tiles

Thanks!
