### ISSUE TITLE
Example for Decomposition API

### ISSUE THREAD

**Issue by VladimirWrites** [android/wear-os-samples#85]
Hi 👋,

I am developing and maintaining Analog Watch Face. https://github.com/VladimirWrites/AnalogWatchFace
A lot of users are asking for the second hand in ambient mode for devices using 3100+ processors, and right now it's only possible using undocumented `DecompositionWatchFaceService`.
I wanted to check with you if there is a plan for long-term support of Decompositions, or if some of the libraries that are currently being developed will replace its functionality.
If Decompositions are there to stay it would be great to have some documentation or examples. 😊

**Comment by yschimke** [comment]
Going to close this out as android.support.wearable.watchface is no longer the relevant library for creating watchfaces.

You possibly already know all this, but for others.

See https://developer.android.com/reference/kotlin/androidx/wear/watchface/package-summary which is used in https://github.com/android/wear-os-samples/tree/main/WatchFaceKotlin

Or the Watch Face Studio https://developer.android.com/training/wearables/wfs

If you think something is missing, you should suggest a feature here https://developer.android.com/jetpack/androidx/releases/wear-watchface#feedback
