### ISSUE TITLE
Cannot resolve symbol 'RemoteIntent' for WearVerifyRemoteApp

### ISSUE THREAD

**Issue by ljunquera** [android/wear-os-samples#87]
I followed the example to use RemoteIntent, but have run into a problem I cannot seem to get past.

I have this import in my class:
import com.google.android.wearable.intent.RemoteIntent;

But am getting an error:

Cannot resolve symbol 'RemoteIntent'
The red lightbulb recommendation is to:

Add Library 'Gradle: com.google.android.support:wearable:2.8.1@aar' to classpath
But when I click on it nothing happens.

And this line in my mobile app gradle dependencies:

compileOnly 'com.google.android.wearable:wearable:2.8.1'
What am I doing wrong?

When I try to build I get this error:

package com.google.android.wearable.intent does not exist error

**Comment by alexvanyo** [comment]
WearVerifyRemoteApp was updated to use the new androidx libraries, instead of the Wearable support libraries, so this issue should no longer happen.
