### ISSUE TITLE
Request: Always on for Compose using AmbientLifeCycleObserver

### ISSUE THREAD

**Issue by bradmartin** [android/wear-os-samples#872]
I've reviewed the AlwaysOnKotlin project and notice it does not use the [AmbientLifeCycleObserver](https://developer.android.com/reference/androidx/wear/ambient/AmbientLifecycleObserver) as suggested in the Android docs.

https://developer.android.com/reference/androidx/wear/ambient/AmbientMode - Deprecation notice here.

I've tried implementing it in my own Compose WearOS app but the watch screen just turns blank instead of moving to ambient mode. It's possible I'm overlooking somethat that has not been updated in the documentation.

Would be great to get a Compose Always On simple example.

**Comment by yschimke** [comment]
See here https://github.com/android/wear-os-samples/pull/880
