### ISSUE TITLE
Wearable.API is not available on this device

### ISSUE THREAD

**Issue by Alexxiaopang** [android/wear-os-samples#902]
I use Mobile  SamSung A54 \ A24  to Install Demo DataLayer 

Log :

2023-09-11 10:44:17.308 22235-22235/com.example.android.wearable.datalayer E/MainActivity: Could not add capability: com.google.android.gms.common.api.ApiException: 17: API: Wearable.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}

wath can i  do?

**Comment by yschimke** [comment]
If it's crashing then it's a bug. But otherwise it's just missing the companion app. You can install from the play store. Galaxy Wearable

**Comment by Koma-Chen** [comment]
i have same issues, I'm not sure if the Google service framework on Chinese phones is a castration version?

**Comment by yschimke** [comment]
You'll need to install a companion app on the phone. 

See https://developer.android.com/training/wearables/creating-app-china#use-other-google-play-services-apis for limitations, and the app stores where you can get the software you need.

We can't help here with specific devices for China market.

**Comment by Alexxiaopang** [comment]
This is Old project ，it use   'com.google.android.gms:play-services-wearable:17.0.0' ，targetAPI 29 is Normal execution！Store need targetAPI  update to  33，I just change targetAPI  to 33 ，it do not work，
this is Log ,same as Demo Log：

Could not add capability: com.google.android.gms.common.api.ApiException: 17: API: Wearable.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}


The following example of the connection, which I have also tried, is invalid，（com.google.android.gms:play-services-wearable:10.2.0）
 https://developer.android.com/training/wearables/creating-app-china#use-other-google-play-services-apis 
 
How can I support devices above TargetApi 29

**Comment by yschimke** [comment]
Raise a bug with logs and hopefully reproduction, this isn't a support forum for wear generally. Sorry.

https://issuetracker.google.com/issues/new?component=460965&template=1422653
