### ISSUE TITLE
WearableListenerService broken in Android 13

### ISSUE THREAD

**Issue by haozes** [android/wear-os-samples#945]
onDataChanged never be called. DataLayerListenerService never be created.

related to this issue:
https://issuetracker.google.com/issues/235538840?pli=1

it said be fixed, but as many other test it still not work.
 
test on: 

 Galaxy Watch 4
 OneUI 5.0
 WearOS 4.0
Google Play services 23.40.14
Wear core services   1.8.1

**Comment by yschimke** [comment]
We can't provide support for the Wearable APIs in this sample project, if you confirm it's happening with this project, post to that bug, or open a new issue linking the old issue and this as a repro.
