### ISSUE TITLE
WearVerifyRemoteApp apps cannot use Google Play

### ISSUE THREAD

**Issue by BoHellgren** [android/wear-os-samples#948]
The Application and Wearable apps cannot both be added as separate Google Play apps since they use the same Applicaion Id.
But  capabilityClient.getCapability and Wearable.getMessageClient(context).sendMessage only work if they have the same Application Id.
Having them in a common Play Store listing using the Multiple APK support does not work either, since the Wearable app must be published in a Wear OS track and the Application app cannot be added there. Catch 22?

**Comment by yschimke** [comment]
Separate tracks for the same listing will have the same package id. This is very common. Apps like confetti have separate tracks, use the data layer.

https://github.com/joreilly/confetti

You can confirm in the fast lane publishing config

https://github.com/joreilly/Confetti/blob/main/fastlane/Fastfile
